#!/usr/bin/env bash
# Build a minimal initramfs for Mackerel-10 NOMMU.
# Requires busybox_nommu to be built first (build_busybox_nommu.sh).
# Outputs:
#   initramfs/          - staging directory with all files
#   initramfs.list      - gen_init_cpio manifest (used by kernel build)
set -e

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
INITRAMFS_DIR="$SCRIPT_DIR/initramfs"
LIST_FILE="$SCRIPT_DIR/initramfs.list"
BUSYBOX="$SCRIPT_DIR/busybox_nommu"

if [ ! -f "$BUSYBOX" ]; then
    echo "ERROR: $BUSYBOX not found. Run build_busybox_nommu.sh first."
    exit 1
fi

file "$BUSYBOX" | grep -q "BFLT" || {
    echo "ERROR: $BUSYBOX is not a bFLT binary."
    file "$BUSYBOX"
    exit 1
}

echo "[*] Creating initramfs staging directory..."
rm -rf "$INITRAMFS_DIR"
mkdir -p "$INITRAMFS_DIR"/{bin,sbin,etc,proc,sys,dev,tmp,root}

echo "[*] Installing busybox..."
cp "$BUSYBOX" "$INITRAMFS_DIR/bin/busybox"
chmod 755 "$INITRAMFS_DIR/bin/busybox"

echo "[*] Creating busybox symlinks..."
for cmd in \
    sh hush \
    echo cat ls mkdir rm cp mv ln touch pwd \
    sleep ps kill killall \
    mount umount \
    hostname uname env \
    dmesg \
    grep sed cut tr wc head tail sort uniq \
    find xargs \
    expr test printf date \
    free df stat readlink basename dirname \
    dd clear reset \
    ; do
    ln -sf busybox "$INITRAMFS_DIR/bin/$cmd"
done
ln -sf ../bin/busybox "$INITRAMFS_DIR/sbin/init"

echo "[*] Writing /etc/inittab..."
cat > "$INITRAMFS_DIR/etc/inittab" <<'EOF'
# Mackerel-10 minimal inittab (busybox init)
# Empty id = run on /dev/console (the boot console = ttyXR0). Avoids opening
# /dev/ttyXR0 directly.
::sysinit:/bin/mount -t devtmpfs dev /dev
::sysinit:/bin/mount -t proc proc /proc
::sysinit:/bin/mount -t sysfs sysfs /sys
::sysinit:/bin/hostname mackerel
::sysinit:/bin/echo "Mackerel-10 uClinux - init OK" > /dev/kmsg
::respawn:-/bin/sh
::restart:/sbin/init
::ctrlaltdel:/bin/reboot
EOF

echo "[*] Writing /etc/passwd..."
echo "root::0:0:root:/root:/bin/sh" > "$INITRAMFS_DIR/etc/passwd"

echo "[*] Writing /etc/profile..."
cat > "$INITRAMFS_DIR/etc/profile" <<'EOF'
export HOME=/root
export PATH=/bin:/sbin
export PS1='\u@mackerel:\w\$ '
cd "$HOME"
EOF

echo "[*] Generating initramfs.list (gen_init_cpio format)..."
cat > "$LIST_FILE" <<EOF
# Mackerel-10 minimal initramfs
# Generated by build_initramfs_nommu.sh — do not edit manually

dir  /proc          0755 0 0
dir  /sys           0755 0 0
dir  /dev           0755 0 0
dir  /bin           0755 0 0
dir  /sbin          0755 0 0
dir  /etc           0755 0 0
dir  /tmp           0777 0 0
dir  /root          0700 0 0

# Device nodes
nod  /dev/console   0600 0 0 c 5 1
nod  /dev/null      0666 0 0 c 1 3
nod  /dev/zero      0666 0 0 c 1 5
nod  /dev/kmsg      0600 0 0 c 1 11
nod  /dev/random    0666 0 0 c 1 8
nod  /dev/urandom   0666 0 0 c 1 9
# /dev/ttyXR0 is created at runtime by devtmpfs (driver uses dynamic major/minor)

# BusyBox binary (bFLT)
file /bin/busybox   ${BUSYBOX} 0755 0 0

# PID 1 = busybox init applet (kernel runs /init; busybox sees argv0 "init")
slink /init         /bin/busybox 0755 0 0

# BusyBox symlinks
slink /sbin/init         /bin/busybox 0755 0 0
slink /bin/sh            busybox 0755 0 0
slink /bin/hush          busybox 0755 0 0
slink /bin/echo          busybox 0755 0 0
slink /bin/cat           busybox 0755 0 0
slink /bin/ls            busybox 0755 0 0
slink /bin/mkdir         busybox 0755 0 0
slink /bin/rm            busybox 0755 0 0
slink /bin/cp            busybox 0755 0 0
slink /bin/mv            busybox 0755 0 0
slink /bin/ln            busybox 0755 0 0
slink /bin/touch         busybox 0755 0 0
slink /bin/pwd           busybox 0755 0 0
slink /bin/sleep         busybox 0755 0 0
slink /bin/ps            busybox 0755 0 0
slink /bin/kill          busybox 0755 0 0
slink /bin/killall       busybox 0755 0 0
slink /bin/mount         busybox 0755 0 0
slink /bin/umount        busybox 0755 0 0
slink /bin/hostname      busybox 0755 0 0
slink /bin/uname         busybox 0755 0 0
slink /bin/dmesg         busybox 0755 0 0
slink /bin/grep          busybox 0755 0 0
slink /bin/sed           busybox 0755 0 0
slink /bin/find          busybox 0755 0 0
slink /bin/date          busybox 0755 0 0
slink /bin/free          busybox 0755 0 0
slink /bin/df            busybox 0755 0 0
slink /bin/env           busybox 0755 0 0
slink /bin/dd            busybox 0755 0 0
slink /bin/clear         busybox 0755 0 0
slink /bin/reset         busybox 0755 0 0

# Config files
file /etc/inittab        ${INITRAMFS_DIR}/etc/inittab  0644 0 0
file /etc/passwd         ${INITRAMFS_DIR}/etc/passwd   0644 0 0
file /etc/profile        ${INITRAMFS_DIR}/etc/profile  0644 0 0
EOF

echo
echo "[+] Done."
echo "    Staging dir: $INITRAMFS_DIR"
echo "    Manifest:    $LIST_FILE"
echo
echo "    Next: run build_kernel_nommu.sh to embed initramfs and build image."
